# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ADC/ADC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC || ORIG_REF_NAME==ADC} -quiet] -quiet

# IP: bd/ADC/ip/ADC_xadc_wiz_0_0/ADC_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_xadc_wiz_0_0 || ORIG_REF_NAME==ADC_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_processing_system7_0_0/ADC_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_processing_system7_0_0 || ORIG_REF_NAME==ADC_processing_system7_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_axi_interconnect_0_0/ADC_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_axi_interconnect_0_0 || ORIG_REF_NAME==ADC_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_rst_ps7_0_50M_0/ADC_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_rst_ps7_0_50M_0 || ORIG_REF_NAME==ADC_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_key_switch_controller_0_0/ADC_key_switch_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_key_switch_controller_0_0 || ORIG_REF_NAME==ADC_key_switch_controller_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_encrypt_0_0/ADC_encrypt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_encrypt_0_0 || ORIG_REF_NAME==ADC_encrypt_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_key_gen_0_0/ADC_key_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_key_gen_0_0 || ORIG_REF_NAME==ADC_key_gen_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_demux_0_0/ADC_demux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_demux_0_0 || ORIG_REF_NAME==ADC_demux_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_xbar_0/ADC_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_xbar_0 || ORIG_REF_NAME==ADC_xbar_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_axi_gpio_0_0 || ORIG_REF_NAME==ADC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_system_ila_0_0/ADC_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_system_ila_0_0 || ORIG_REF_NAME==ADC_system_ila_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_auto_pc_0/ADC_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_auto_pc_0 || ORIG_REF_NAME==ADC_auto_pc_0} -quiet] -quiet

# XDC: d:/Downloads/myproject_working_bitstream/myproject/Prime_Generation.gen/sources_1/bd/ADC/ADC_ooc.xdc
