@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Apr 30 16:39:09 -0400 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim key_gen_tb_behav -key {Behavioral:sim_1:Functional:key_gen_tb} -tclbatch key_gen_tb.tcl -view C:/Users/saaha/Documents/Code/Research/TCL_Test_Merge/myproject/myproject.srcs/sim_1/imports/src/prime_tb_behav.wcfg -view C:/Users/saaha/Documents/Code/Research/TCL_Test_Merge/myproject/myproject.srcs/sim_1/imports/src/key_gen_tb_behav.wcfg -log simulate.log"
call xsim  key_gen_tb_behav -key {Behavioral:sim_1:Functional:key_gen_tb} -tclbatch key_gen_tb.tcl -view C:/Users/saaha/Documents/Code/Research/TCL_Test_Merge/myproject/myproject.srcs/sim_1/imports/src/prime_tb_behav.wcfg -view C:/Users/saaha/Documents/Code/Research/TCL_Test_Merge/myproject/myproject.srcs/sim_1/imports/src/key_gen_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
