# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Downloads/myproject_working_bitstream/myproject/myproject.srcs/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0.xci
# IP: The module: 'ADC_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Downloads/myproject_working_bitstream/myproject/Prime_Generation.gen/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Downloads/myproject_working_bitstream/myproject/Prime_Generation.gen/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Downloads/myproject_working_bitstream/myproject/Prime_Generation.gen/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Downloads/myproject_working_bitstream/myproject/myproject.srcs/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0.xci
# IP: The module: 'ADC_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Downloads/myproject_working_bitstream/myproject/Prime_Generation.gen/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Downloads/myproject_working_bitstream/myproject/Prime_Generation.gen/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Downloads/myproject_working_bitstream/myproject/Prime_Generation.gen/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
